name: SwiftUITemplate
#packages:
#  KeychainAccess:
#    url: https://github.com/kishikawakatsumi/KeychainAccess.git
#    exactVersion: 4.2.2
options:
  bundleIdPrefix: com.shotach
deploymentTarget: "13.0"
attributes:
  ORGANIZATIONNAME: "Shota Shimazu"
targets:
  SwiftUITemplate:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - SwiftUITemplate
    settings:
      base:
        MARKETING_VERSION: 0.0.1
        CURRENT_PROJECT_VERSION: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.shotach.ios-template
        INFOPLIST_FILE: SwiftUITemplate/Info.plist
        SUPPORTS_MACCATALYST: YES
        "IPHONEOS_DEPLOYMENT_TARGET[sdk=macosx*]": 14.2
    scheme:
      testTargets:
        - SwiftUITemplateTests
        - SwiftUITemplateTests
    #dependencies:
      #- target: SampleFramework
      #- sdk: MapKit.framework
      #- package: KeychainAccess
  Tests:
    type: bundle.unit-test
    platform: iOS
    sources: SwiftUITemplateTests
    dependencies:
      - target: SwiftUITemplateTests
  UITests:
    type: bundle.ui-testing
    platform: iOS
    sources: SwiftUITemplateUITests
    dependencies:
      - target: SwiftUITemplateUITests
